import java.sql.Connection;
import java.sql.DriverManager;
public class QA
{
	 
	public static void main(String[] args)
	{
	//Connection1 cn = new Connection1();
		//	cn.getConnection();
		//MemberService mem = new MemberService();
			//mem.RegisterNewMember();
	 // QuestionService que = new QuestionService();
			//que.ShowAllQuestions();
		  //que.PostQuestion();
			//que.ShowQuestionAnswers();
		//que.ShowQuestionAnswersName();
	  		 //que.UpdateQuestionStatus();
	//AnswerService ans = new AnswerService();
	  	 // ans.PostAnswer();
		//	ans.ShowAnswers();
	  //  ans.UpdateAnswerStatus();
	}
	
	
	
	
	
	


}